'use client'
import { useState, Suspense } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useRouter, useSearchParams } from 'next/navigation'
import Link from 'next/link'

const termsContent = [
    {
        title: 'A. Product Eligibility',
        points: [
            'All food products listed are still edible and safe for consumption.',
            'Products sold are not past their expiration dates.',
            'Product information must be entered honestly and accurately.',
        ]
    },
    {
        title: 'B. Partner Responsibilities',
        points: [
            'I take full responsibility for the quality, hygiene, and safety of the food.',
            'PlateUp! acts solely as a connecting platform and is not the food producer.',
            'All risks associated with product consumption are the sole responsibility of the partner.',
        ]
    },
    {
        title: 'C. System & AI Usage',
        points: [
            'Shelf-life estimation and pricing are generated by AI and serve as recommendations only.',
            'I remain responsible for manually ensuring food quality before it is sold.',
            'I will not misuse the system to sell products that do not meet the standards.',
        ]
    },
    {
        title: 'D. Pricing & Transactions',
        points: [
            'Prices may be adjusted to effectively reduce food waste.',
            'I will not engage in price manipulation that harms consumers or the platform.',
        ]
    },
    {
        title: 'E. Data & Documentation',
        points: [
            'I provide valid business data (business name, address, contact details).',
            'I will upload a truthful Statement Letter that can be legally accounted for.',
            'I agree that my data will be used for the platform\'s operational purposes.',
        ]
    },
    {
        title: 'F. Compliance & Sanctions',
        points: [
            'I agree to comply with all PlateUp! platform policies.',
            'Violations may result in: Account deactivation, Product removal, Platform access restriction.',
        ]
    },
]

function TermsModal({
    role,
    onClose,
    onAgree,
}: {
    role: string
    onClose: () => void
    onAgree: () => void
}) {
    const [agreedInModal, setAgreedInModal] = useState(false)

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4">
            <div className="w-full max-w-2xl bg-white rounded-2xl shadow-xl overflow-hidden">

                {/* Modal Header */}
                <div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between">
                    <h3 className="text-base font-bold text-gray-900">
                        Terms & Conditions for PlateUp! {role === 'partner' ? 'Partners' : 'Users'}
                    </h3>
                    <button onClick={onClose} className="text-gray-400 hover:text-gray-600 text-xl leading-none">×</button>
                </div>

                {/* Modal Body — scrollable */}
                <div className="px-6 py-4 max-h-[50vh] overflow-y-auto">
                    <p className="text-sm text-gray-500 mb-4">
                        By registering on the PlateUp! platform, I hereby agree to the following terms:
                    </p>
                    <div className="space-y-4">
                        {termsContent.map((section, i) => (
                            <div key={i}>
                                <p className="text-sm font-semibold text-gray-900 mb-1">{section.title}</p>
                                <ul className="space-y-1 pl-3">
                                    {section.points.map((point, j) => (
                                        <li key={j} className="flex gap-2 text-xs text-gray-600">
                                            <span className="text-[#3a7d44] shrink-0 mt-0.5">•</span>
                                            {point}
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        ))}
                    </div>

                    {/* Statement of Consent */}
                    <div className="mt-6 p-4 bg-gray-50 rounded-xl">
                        <p className="text-sm font-medium text-gray-900 mb-3">Statement of Consent</p>
                        <div className="flex items-start gap-2">
                            <input
                                type="checkbox"
                                id="modalAgree"
                                checked={agreedInModal}
                                onChange={e => setAgreedInModal(e.target.checked)}
                                className="mt-0.5 accent-[#3a7d44]"
                            />
                            <label htmlFor="modalAgree" className="text-xs text-gray-600 cursor-pointer leading-relaxed">
                                By checking this box, I agree to the Terms and Conditions and acknowledge my responsibilities.
                            </label>
                        </div>
                    </div>
                </div>

                {/* Modal Footer */}
                <div className="px-6 py-4 border-t border-gray-100 flex gap-3">
                    <button
                        onClick={onClose}
                        className="flex-1 py-2.5 text-sm text-gray-500 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
                    >
                        Cancel
                    </button>
                    <button
                        onClick={() => { if (agreedInModal) onAgree() }}
                        disabled={!agreedInModal}
                        className="flex-1 py-2.5 text-sm font-medium text-white bg-[#3a7d44] rounded-lg hover:bg-[#2d6435] transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
                    >
                        Complete Registration
                    </button>
                </div>
            </div>
        </div>
    )
}

function RegisterForm() {
    const supabase = createClient()
    const router = useRouter()
    const searchParams = useSearchParams()
    const role = searchParams.get('role') ?? 'customer'

    const [form, setForm] = useState({
        fullName: '', email: '', password: '', confirmPassword: ''
    })
    const [termsChecked, setTermsChecked] = useState(false)
    const [showModal, setShowModal] = useState(false)
    const [pendingAction, setPendingAction] = useState<'email' | 'google' | null>(null)
    const [loading, setLoading] = useState(false)
    const [error, setError] = useState<string | null>(null)

    const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        setForm(prev => ({ ...prev, [e.target.name]: e.target.value }))
    }

    const validateForm = () => {
        if (!form.fullName || !form.email || !form.password || !form.confirmPassword) {
            setError('Please fill in all fields')
            return false
        }
        if (form.password !== form.confirmPassword) {
            setError('Password tidak cocok')
            return false
        }
        if (form.password.length < 6) {
            setError('Password minimal 6 karakter')
            return false
        }
        return true
    }

    const handleEmailSubmit = (e: React.FormEvent) => {
        e.preventDefault()
        setError(null)
        if (!validateForm()) return

        if (!termsChecked) {
            setError('Please agree to Terms of Service first')
            return
        }

        if (role === 'partner') {
            // Partner → tampilkan modal terms dulu
            setPendingAction('email')
            setShowModal(true)
        } else {
            // Customer → langsung buat akun
            handleDirectRegister()
        }
    }

    const handleGoogleClick = () => {
        setError(null)

        if (!termsChecked) {
            setError('Please agree to Terms of Service before continuing')
            return
        }

        if (role === 'partner') {
            // Partner → modal dulu
            setPendingAction('google')
            setShowModal(true)
        } else {
            // Customer → langsung Google
            handleDirectGoogle()
        }
    }

    // Customer register langsung tanpa modal
    const handleDirectRegister = async () => {
        setLoading(true)
        const { data, error: signUpError } = await supabase.auth.signUp({
            email: form.email,
            password: form.password,
            options: { data: { full_name: form.fullName, role } }
        })

        if (signUpError) {
            setError(signUpError.message)
            setLoading(false)
            return
        }

        if (data.user) {
            // Insert profile
            await supabase.from('profiles').upsert({
                id: data.user.id,
                full_name: form.fullName,
                role,
            })

            // Paksa refresh session sebelum redirect
            await supabase.auth.getSession()

            router.push(role === 'partner' ? '/dashboard/partner' : '/dashboard/customer')
            router.refresh()
        } else {
            // Email confirmation aktif — kasih tahu user
            setError('Please check your email to confirm your account before logging in.')
            setLoading(false)
        }
    }

    // Customer Google langsung tanpa modal
    const handleDirectGoogle = async () => {
        document.cookie = `pending_role=customer; path=/; max-age=300`
        const { error } = await supabase.auth.signInWithOAuth({
            provider: 'google',
            options: { redirectTo: `${window.location.origin}/auth/callback` }
        })
        if (error) setError(error.message)
    }
    // Dipanggil setelah user setuju di modal
    const handleModalAgree = async () => {
        setShowModal(false)

        if (pendingAction === 'email') {
            setLoading(true)
            const { data, error: signUpError } = await supabase.auth.signUp({
                email: form.email,
                password: form.password,
                options: { data: { full_name: form.fullName, role } }
            })

            if (signUpError) { setError(signUpError.message); setLoading(false); return }

            if (data.user) {
                await supabase.from('profiles').upsert({
                    id: data.user.id,
                    full_name: form.fullName,
                    role,
                })
            }
            router.push(role === 'partner' ? '/dashboard/partner' : '/dashboard/customer')
        }

        if (pendingAction === 'google') {
            // Set cookie role sebelum redirect Google
            document.cookie = `pending_role=${role}; path=/; max-age=300`
            const { error } = await supabase.auth.signInWithOAuth({
                provider: 'google',
                options: { redirectTo: `${window.location.origin}/auth/callback` }
            })
            if (error) setError(error.message)
        }
    }

    return (
        <>
            {/* Terms Modal */}
            {showModal && (
                <TermsModal
                    role={role}
                    onClose={() => { setShowModal(false); setPendingAction(null) }}
                    onAgree={handleModalAgree}
                />
            )}

            <div className="min-h-[calc(100vh-140px)] flex items-center justify-center bg-[#F5F5F5] py-10 px-4">
                <div className="w-full max-w-md bg-white rounded-2xl shadow-sm border border-gray-100 p-8">

                    {/* Badge role */}
                    <div className="flex justify-center mb-5">
                        <span className="px-4 py-1.5 rounded-full text-xs font-medium bg-[#eaf3de] text-[#3a7d44]">
                            {role === 'partner' ? '🏪 Register as Partner' : '🍱 Register as Customer'}
                        </span>
                    </div>

                    <h2 className="text-2xl font-bold text-gray-900 text-center mb-1">
                        {role === 'partner' ? 'Become a Partner' : 'Create Account'}
                    </h2>
                    <p className="text-sm text-gray-500 text-center mb-6">
                        {role === 'partner'
                            ? 'List your surplus food and reach students near you.'
                            : 'Join PlateUp! and start finding affordable food today.'}
                    </p>

                    {error && (
                        <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-600">
                            {error}
                        </div>
                    )}

                    <form onSubmit={handleEmailSubmit} className="space-y-4">
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">Full Name</label>
                            <input type="text" name="fullName" value={form.fullName}
                                onChange={handleChange} placeholder="Enter your full name"
                                className="w-full px-4 py-2.5 text-sm border border-gray-200 rounded-lg bg-white text-gray-900 focus:outline-none focus:ring-2 focus:ring-[#3a7d44]/20 focus:border-[#3a7d44]" />
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">Email Address</label>
                            <input type="email" name="email" value={form.email}
                                onChange={handleChange} placeholder="Your Email"
                                className="w-full px-4 py-2.5 text-sm border border-gray-200 rounded-lg bg-white text-gray-900 focus:outline-none focus:ring-2 focus:ring-[#3a7d44]/20 focus:border-[#3a7d44]" />
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">Password</label>
                            <input type="password" name="password" value={form.password}
                                onChange={handleChange} placeholder="Create a strong password"
                                className="w-full px-4 py-2.5 text-sm border border-gray-200 rounded-lg bg-white text-gray-900 focus:outline-none focus:ring-2 focus:ring-[#3a7d44]/20 focus:border-[#3a7d44]" />
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">Confirm Password</label>
                            <input type="password" name="confirmPassword" value={form.confirmPassword}
                                onChange={handleChange} placeholder="Re-enter your password"
                                className="w-full px-4 py-2.5 text-sm border border-gray-200 rounded-lg bg-white text-gray-900 focus:outline-none focus:ring-2 focus:ring-[#3a7d44]/20 focus:border-[#3a7d44]" />
                        </div>

                        <div className="text-right text-sm text-gray-500">
                            Forgot your password?
                        </div>

                        <button type="submit" disabled={loading}
                            className="w-full py-3 bg-[#3a7d44] hover:bg-[#2d6435] text-white text-sm font-medium rounded-lg transition-colors disabled:opacity-60">
                            {loading ? 'Creating account...' : 'Create Account'}
                        </button>
                    </form>

                    {/* Or sign up with */}
                    <div className="flex items-center gap-3 my-5">
                        <div className="flex-1 h-px bg-gray-200" />
                        <span className="text-xs text-gray-400">Or sign up with</span>
                        <div className="flex-1 h-px bg-gray-200" />
                    </div>

                    {/* Google Button */}
                    <button
                        onClick={handleGoogleClick}
                        className="w-full py-2.5 bg-gray-50 hover:bg-gray-100 border border-gray-200 text-sm text-gray-700 rounded-lg flex items-center justify-center gap-2 transition-colors"
                    >
                        <svg width="18" height="18" viewBox="0 0 24 24">
                            <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" />
                            <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" />
                            <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l3.66-2.84z" />
                            <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" />
                        </svg>
                        Continue with Google
                    </button>

                    {/* Already have account */}
                    <p className="text-center text-sm text-gray-500 mt-5">
                        Already have an account?{' '}
                        <Link href="/auth/login" className="text-[#3a7d44] font-medium">Sign in</Link>
                    </p>

                    {/* Terms checkbox di bawah */}
                    <div className="flex items-start gap-2 mt-4 pt-4 border-t border-gray-100">
                        <input
                            type="checkbox"
                            id="terms"
                            checked={termsChecked}
                            onChange={e => setTermsChecked(e.target.checked)}
                            className="mt-0.5 accent-[#3a7d44]"
                        />
                        <label htmlFor="terms" className="text-xs text-gray-500 leading-relaxed cursor-pointer">
                            By signing up, you agree to our{' '}
                            <Link href="/terms" className="text-[#3a7d44] hover:underline">Terms of Service</Link>
                            {' '}and{' '}
                            <Link href="/privacy" className="text-[#3a7d44] hover:underline">Privacy Policy</Link>.
                        </label>
                    </div>
                </div>
            </div>
        </>
    )
}

export default function RegisterPage() {
    return (
        <Suspense fallback={<div className="min-h-screen flex items-center justify-center">Loading...</div>}>
            <RegisterForm />
        </Suspense>
    )
}