'use client'
import { useState, useEffect } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useRouter } from 'next/navigation'

export default function PartnerTermsPage() {
    const supabase = createClient()
    const router = useRouter()
    const [agreed, setAgreed] = useState(false)
    const [loading, setLoading] = useState(false)
    const [error, setError] = useState<string | null>(null)
    const [hasPendingData, setHasPendingData] = useState(false)

    useEffect(() => {
        const raw = sessionStorage.getItem('pendingRegister')
        setHasPendingData(!!raw)
    }, [])

    const handleEmailRegister = async () => {
        if (!agreed) { setError('Please check the agreement box'); return }
        setLoading(true)

        const raw = sessionStorage.getItem('pendingRegister')
        if (!raw) { router.push('/register?role=partner'); return }

        const { fullName, email, password } = JSON.parse(raw)

        const { data, error: signUpError } = await supabase.auth.signUp({
            email,
            password,
            options: {
                data: { full_name: fullName, role: 'partner' }
            }
        })

        if (signUpError) { setError(signUpError.message); setLoading(false); return }

        if (data.session) {
            await supabase.from('profiles').upsert({
                id: data.user!.id,
                full_name: fullName,
                role: 'partner',
            })
            sessionStorage.removeItem('pendingRegister')
            router.push('/dashboard/partner')
            router.refresh()

        } else if (data.user && !data.session) {
            sessionStorage.removeItem('pendingRegister')
            setError('Please check your email to confirm your account, then log in.')
            setLoading(false)

        } else {
            setError('Registration failed. Please try again.')
            setLoading(false)
        }
    }

    const handleGoogleRegister = async () => {
        if (!agreed) { setError('Please check the agreement box'); return }
        document.cookie = `pending_role=partner; path=/; max-age=300`
        const { error } = await supabase.auth.signInWithOAuth({
            provider: 'google',
            options: { redirectTo: `${window.location.origin}/auth/callback` }
        })
        if (error) setError(error.message)
    }

    return (
        <div className="min-h-[calc(100vh-140px)] flex items-center justify-center bg-[#F5F5F5] py-10 px-4">
            <div className="w-full max-w-2xl bg-white rounded-2xl shadow-sm border border-gray-100 p-8">

                <h2 className="text-xl font-bold text-gray-900 text-center mb-1">
                    Terms & Conditions for PlateUp! Partners
                </h2>
                <p className="text-sm text-gray-500 text-center mb-6">
                    By registering as a partner, I agree to the following terms:
                </p>

                <div className="space-y-4 text-sm text-gray-700 max-h-72 overflow-y-auto pr-2 mb-6 border border-gray-100 rounded-xl p-4">
                    {[
                        {
                            title: 'A. Product Eligibility',
                            points: [
                                'All food products listed are still edible and safe for consumption.',
                                'Products sold are not past their expiration dates.',
                                'Product information must be entered honestly and accurately.',
                            ]
                        },
                        {
                            title: 'B. Partner Responsibilities',
                            points: [
                                'I take full responsibility for the quality, hygiene, and safety of the food.',
                                'PlateUp! acts solely as a connecting platform and is not the food producer.',
                                'All risks associated with product consumption are the sole responsibility of the partner.',
                            ]
                        },
                        {
                            title: 'C. System & AI Usage',
                            points: [
                                'Shelf-life estimation and pricing are generated by AI and serve as recommendations only.',
                                'I remain responsible for manually ensuring food quality before it is sold.',
                                'I will not misuse the system to sell products that do not meet the standards.',
                            ]
                        },
                        {
                            title: 'D. Pricing & Transactions',
                            points: [
                                'Prices may be adjusted to effectively reduce food waste.',
                                'I will not engage in price manipulation that harms consumers or the platform.',
                            ]
                        },
                        {
                            title: 'E. Data & Documentation',
                            points: [
                                'I provide valid business data (business name, address, contact details).',
                                'I will upload a truthful Statement Letter that can be legally accounted for.',
                                "I agree that my data will be used for the platform's operational purposes.",
                            ]
                        },
                        {
                            title: 'F. Compliance & Sanctions',
                            points: [
                                'I agree to comply with all PlateUp! platform policies.',
                                'Violations may result in: Account deactivation, Product removal, Platform access restriction.',
                            ]
                        },
                    ].map((section, i) => (
                        <div key={i}>
                            <p className="font-semibold text-gray-900 mb-1">{section.title}</p>
                            <ul className="space-y-1 pl-3">
                                {section.points.map((point, j) => (
                                    <li key={j} className="flex gap-2 text-gray-600 text-xs">
                                        <span className="text-[#3a7d44] mt-0.5 shrink-0">•</span>
                                        {point}
                                    </li>
                                ))}
                            </ul>
                        </div>
                    ))}
                </div>

                <div className="flex items-start gap-2 p-4 bg-gray-50 rounded-xl mb-4">
                    <input
                        type="checkbox"
                        id="partnerAgree"
                        checked={agreed}
                        onChange={e => setAgreed(e.target.checked)}
                        className="mt-0.5 accent-[#3a7d44]"
                    />
                    <label htmlFor="partnerAgree" className="text-sm text-gray-600 leading-relaxed cursor-pointer">
                        By checking this box, I agree to the Terms and Conditions and acknowledge my responsibilities as a Partner.
                    </label>
                </div>

                {error && (
                    <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-600">
                        {error}
                    </div>
                )}

                <div className={`space-y-3 transition-opacity ${agreed ? 'opacity-100' : 'opacity-40 pointer-events-none'}`}>
                    {hasPendingData && (
                        <button
                            onClick={handleEmailRegister}
                            disabled={loading || !agreed}
                            className="w-full py-3 bg-[#3a7d44] hover:bg-[#2d6435] text-white text-sm font-medium rounded-lg transition-colors disabled:opacity-60"
                        >
                            {loading ? 'Creating account...' : 'Complete Registration with Email'}
                        </button>
                    )}

                    <button
                        onClick={handleGoogleRegister}
                        disabled={!agreed}
                        className="w-full py-2.5 bg-gray-50 hover:bg-gray-100 border border-gray-200 text-sm text-gray-700 rounded-lg flex items-center justify-center gap-2 transition-colors disabled:opacity-60"
                    >
                        <svg width="18" height="18" viewBox="0 0 24 24">
                            <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" />
                            <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" />
                            <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l3.66-2.84z" />
                            <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" />
                        </svg>
                        Register as Partner with Google
                    </button>

                    {!hasPendingData && (
                        <p className="text-xs text-gray-400 text-center">
                            Or{' '}
                            <button
                                onClick={() => router.push('/register?role=partner')}
                                className="text-[#3a7d44] hover:underline"
                            >
                                fill in your details first
                            </button>
                            {' '}to register with email.
                        </p>
                    )}
                </div>

                <button
                    onClick={() => router.back()}
                    className="w-full mt-3 py-2 text-sm text-gray-400 hover:text-gray-600 transition-colors"
                >
                    ← Back
                </button>
            </div>
        </div>
    )
}